services:
  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    ports:
      - "80:80"
      - "443:443"  # Nếu sử dụng HTTPS, bỏ dòng này nếu không
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /home/ec2-user/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - minio-net
    restart: always

networks:
  minio-net:
    driver: bridge